spring.application.name=feliz-aniversario-api

spring.datasource.url=jdbc:postgresql://localhost:5432/feliz_aniversario_db
spring.datasource.username=postgres
spring.datasource.password=dhmeli
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

